##
# Server
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server
# https://github.com/spring-projects/spring-restdocs/issues/710
# https://www.baeldung.com/exception-handling-for-rest-with-spring#spring-boot
# https://reflectoring.io/spring-boot-exception-handling/
##
server:
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include-exception: false
    port: 8080
    servlet:
        context-path: /

##
# Spring Application
##
spring:
    output:
        ansi:
            enabled: ALWAYS
    ##
    # https://github.com/zalando/problem-spring-web/issues/732
    ##
    web:
        resources:
            add-mappings: false
    mvc:
        throw-exception-if-no-handler-found: true

##
# Spring Actuator
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
##
management:
    endpoints:
        jmx:
            exposure:
                include: "*"
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
            show-components: always
            ##
            # Kubernetes Probes
            # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
            ##
            probes:
                enabled: true
                add-additional-paths: true
##
# Spring Cloud AWS
# https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/appendix.html
##
cloud:
    aws:
        stack:
            auto: false
            enabled: false
        credentials:
            access-key:
            secret-key:
        region:
            static: us-east-1
        sqs:
            endpoint:
            listener:
                auto-startup: true
                fail-on-missing-queue: false
                default-deletion-policy: NO_REDRIVE
                max-number-of-messages: 10
                visibility-timeout: 30  # 30s
                wait-timeout: 20        # 20s
                back-off-time: 10000    # 10s

logging:
    level:
        io.awspring.cloud.messaging.core: debug
        io.awspring.cloud.messaging.listener: debug
        com.amazonaws.services.sqs: debug

integration.aws.sqs.producer-queue: integration-import
integration.aws.sqs.consumer-queue: integration-import